kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud-ninja-frontend
  namespace: kubernetes-aks1
  labels:
    App: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      App: cloud-ninja-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        App: cloud-ninja-frontend
    spec:
      containers:
        - name: cloud-ninja-frontend
          image: 'ajay185/frontend:4'
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER
              value: 'http://cloud-ninja-backend'
          resources:
            limits:
              cpu: 200m
              memory: 2562Mi
            requests:
              cpu: 100m
              memory: 50Mi
